### ISSUE TITLE
Screenshot issue with ksnip

### ISSUE THREAD

**Issue by yochananmarqos** [pop-os/xdg-desktop-portal-cosmic#2]
I just built cosmic-epoch from https://github.com/pop-os/cosmic-epoch/commit/277cf9e3f1e810d8c66a16bb6b21cc102e0f400f and followed the [screenshot instructions](https://github.com/pop-os/cosmic-epoch#screenshots). However, `ksnip` isn't playing nice:

```
❯ ksnip -t
Critical: Unknown wayland platform, using default wayland Image Grabber.
Warning: Unable to find any translation files for ksnip.
Warning: Unable to find any translation files for kImageAnnotator.
Warning: Unsupported Capture Mode selected, falling back to full screen.
Critical: Error: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop
```

`ksnip` 1.10.0-1
`qt5-wayland` 5.15.8+kde+r60-1

```
❯ pacman -Fx org.freedesktop.portal.Screenshot
extra/xdg-desktop-portal 1.16.0-1 [installed]
    usr/share/dbus-1/interfaces/org.freedesktop.portal.Screenshot.xml
```

**Comment by Drakulix** [comment]
> Critical: Error: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop

This looks more like the portal is not running on your system. A possible reason could be, that the portal is crashing on startup.
If that is the case, you might be able to get some logs by running `journalctl --user _EXE=/usr/libexec/xdg-desktop-portal-cosmic`.

Another possible reason is, that the portal simply wasn't started. Given we only added the portal to our session autostart [a couple of weeks ago](https://github.com/pop-os/cosmic-session/commit/3094e4698efef6fa4ae3c52c8ac1a6de39f40687) and this issue is already two weeks old (sorry!), you maybe simply need to update to get the latest cosmic-session package for this to start working.

If the issue persists, please try to start the cosmic-portal manually in a terminal, restart the generic-portal and try ksnip again. If that works something is broken with starting up the portal, if it doesn't please attach the output of all three commands:
```
/usr/libexec/xdg-desktop-portal-cosmic &
systemctl --user restart xdg-desktop-portal;
ksnip -t
```

**Comment by Drakulix** [comment]
> ❯ pacman -Fx org.freedesktop.portal.Screenshot

I just saw, that you are likely running archlinux given the `pacman` output.
It may very well be, that the `cosmic-session` submodule in `cosmic-epoch` is simply too old to contain the necessary commit to start the portal. I will check later today.

**Comment by yochananmarqos** [comment]
It's working now with https://github.com/pop-os/cosmic-epoch/commit/f0b63f7286cffb1445873860ed9cecaf2b569988. :+1:
